# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=grid_search experiment=example

defaults:
  - override /hydra/sweeper: basic

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/roc_auc_best"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    # define hyperparameter search space
    params:
      model.optimizer.lr: choice(0.001, 0.0001, 0.00001)
      data.batch_size: choice(300)
      model.optimizer.weight_decay: choice(0.0001, 0.0)
